Vagrant.configure("2") do |config|
  config.vm.provider "docker" do |docker, override|
    # docker doesnt use boxes
    override.vm.box = nil
    # Make sure the Dockerfile is in the same directory has the Vagrantfile
    docker.build_dir = "."

    # Make sure it sets up ssh with the Dockerfile
    # Vagrant is pretty dependent on ssh
    override.ssh.insert_key = true
    docker.has_ssh = true

    # Configure Docker to allow access to more resources
    docker.privileged = true
  end
end
