Vagrant.configure("2") do |config|
  vm_name = "linux-x86-ebpf"
  config.vm.hostname = vm_name

  # Network configuration
  config.vm.network :private_network, type: "dhcp", docker_network__internal: true

  config.vm.provider "docker" do |docker, override|
    # Resources
    docker.create_args = ['--cpuset-cpus=2']
    docker.create_args = ['--memory=6g']
    # Docker doesnt use boxes
    override.vm.box = nil
    # Make sure the Dockerfile is in the same directory has the Vagrantfile
    docker.build_dir = "."
    # Make sure it sets up ssh with the Dockerfile
    docker.has_ssh = true
    # Make sure the container keeps running
    docker.remains_running = true
    # Make sure it runs with -i -t (TTY)
    docker.create_args = ["-i", "-t"]
  end
end
