Vagrant.configure("2") do |config|
  vm_name = "vagrant-docker"
  config.vm.hostname = vm_name
  config.vm.provider "docker" do |docker, override|
    # Docker doesnt use boxes
    override.vm.box = nil
    # Make sure the Dockerfile is in the same directory has the Vagrantfile
    docker.build_dir = "."
    # Make sure it sets up ssh with the Dockerfile
    docker.has_ssh = true
    # Make sure the container keeps running
    docker.remains_running = true
    # Make sure it runs with -i -t (TTY)
    docker.create_args = ["-i", "-t"]
  end
end
