[package]
name = "redbpf-tut"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "tutmon"
path = "src/tutmon/main.rs"
required-features = ["probes"]